### ISSUE TITLE
pop back animation is not correct 

### ISSUE THREAD

**Issue by gitcrosstrack** [lkzhao/Hero#148] opened 2017-03-15 09:19 UTC
I use the demo code  to display cascade fading&scaling cells. When the view controller is loaded, it works perfectly, but after I push to next page in navigation controller , I just pressed back button, the cell is transitioning to the incorrect position.

![cap](https://cloud.githubusercontent.com/assets/19166692/23942358/f5461d5e-09a6-11e7-9621-6af966330b1c.gif)

**Comment by gitcrosstrack** [comment] 2017-03-15 09:21
`
class ViewController: UIViewController,UICollectionViewDelegateFlowLayout,UICollectionViewDataSource{

    @IBOutlet weak var collectionView: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        collectionView.register(UINib.init(nibName: "YDDeviceTypeCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "DeviceType")
        collectionView.heroModifiers = [.cascade]
        
        // Do any additional setup after loading the view.
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.setNavigationBarHidden(true, animated: false)
    }
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.navigationController?.setNavigationBarHidden(false, animated:false)
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    public func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int{
        return 3;
    }
    
    
    // The cell that is returned must be retrieved from a call to -dequeueReusableCellWithReuseIdentifier:forIndexPath:
    public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell{
        let identifier = "DeviceType"
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: identifier, for: indexPath) as! YDDeviceTypeCollectionViewCell
        let row = indexPath.row
        var filename:String!
        var title:String!
        switch row {
        case 0:
            filename = "menu_lock_normal";
            title = "智能门锁";
        case 1:
            filename = "menu_sensor_normal";
            title = "安防门磁";
        case 2:
            filename = "menu_camera_normal";
            title = "智能猫眼";
        default: break
            
        }
        cell.imageView.image = UIImage(named: filename)
        cell.nameLbl.text = title
        cell.heroID = "\(indexPath)"
        
        cell.heroModifiers = [.fade,.scale(0.5)] //,.scale(0.5)
        
        return cell
    }
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize{
        return CGSize(width: 350, height: 201)
    }
    
        
    
    @IBAction func cancel(_ sender: Any) {
        
        if self.navigationController!.viewControllers.count > 1{
            let _ = self.navigationController?.popViewController(animated: true)
        }else{
            self.navigationController?.dismiss(animated: true, completion: nil)
        }
    }


}

`
the demo code is very simple...

**Comment by gitcrosstrack** [comment] 2017-03-15 09:48
oh ,one more point: when I use the 0.31 version, it is ok.It happens when I pod update to the newest 0.34

**Comment by czater** [comment] 2017-03-15 21:03
same here...my animation behave as yours but it is moved to right :/ and it happens after update

**Comment by lkzhao** [comment] 2017-03-15 22:01
Thanks for reporting this. Already know the cause. Will fix in the next version.

**Comment by lkzhao** [comment] 2017-03-16 22:43
Should be fixed. Can you guys verify?

**Comment by gitcrosstrack** [comment] 2017-03-17 02:42
It's ok now.Thank you very much @lkzhao

**Comment by czater** [comment] 2017-03-22 18:16
Yep, it works fine, thanks @lkzhao

**Comment by farzadshbfn** [comment] 2017-04-16 14:42
Suggesting to close the issue

**Closed** 2017-04-17 13:58 UTC
