### ISSUE TITLE
Not support orientation for now

### ISSUE THREAD

**Issue by ZhouBoo** [lkzhao/Hero#60] opened 2017-01-29 01:42 UTC
If your change device orientation, then BOOM...
![img_0551](https://cloud.githubusercontent.com/assets/6223098/22401244/24d46904-e607-11e6-8b70-ddfa024d69de.PNG)

**Comment by lkzhao** [comment] 2017-01-29 17:37
I am not seeing this. Did it happen during a transition?

**Comment by lkzhao** [comment] 2017-01-29 17:37
![simulator screen shot jan 29 2017 12 37 43 pm](https://cloud.githubusercontent.com/assets/3359850/22406342/bc633c92-e61f-11e6-9569-8789095236d4.png)

**Comment by ZhouBoo** [comment] 2017-01-30 05:14
@lkzhao  hum.. it happen after a transition. 
I present to a new view controller and change orientation after transition.
It happens when I dismiss this view controller.

**Comment by saeros** [comment] 2017-02-02 09:09
Hi, I've noticed the same issue.

In my case, say I start the app in landscape, push a new controller on the navigation controller stack, rotate to portrait and pop the new controller, then the previous controller frame is incorrect and I get a black area on the right side (same behaviour if I start in portait and rotate to landscape, the black area is at the bottom).

**Comment by lkzhao** [comment] 2017-02-02 15:33
Ok. It is probably a regression from fixing https://github.com/lkzhao/Hero/issues/36. I will fix it today.

**Comment by lkzhao** [comment] 2017-02-02 16:02
Should be fixed on the latest master:

```ruby
pod "Hero", :git=>"https://github.com/lkzhao/Hero.git"
```

**Comment by saeros** [comment] 2017-02-02 17:58
Can't reproduce the issue with the latest version (0.1.3)

Cheers :thumbsup:

**Closed** 2017-02-02 20:26 UTC
Labels: need info
